name: CI/CD Pipeline

on:
  # push:
  #   branches:
  #     - main
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Create .env file
      run: |
        echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
        echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env

    - name: Run tests
      run: |
        python -m unittest discover

    - name: Build Docker image
      run: |
        docker build -t your_docker_image .

    - name: Push Docker image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push your_docker_image

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
